#!/bin/bash
# piderman piderman bash shell piderman

# System
# ------------------------------------------------------------------------------
piModel() {
  echo "$(tr -d '\0' </proc/device-tree/model)"
}

piPrint() {
  echo -n "Model: $(piModel)"
}


# CPU
# ------------------------------------------------------------------------------
cpuTemperatureC() {
  echo "scale=2; $(cat /sys/class/thermal/thermal_zone0/temp)/1000" | bc
}

cpuTemperatureF() {
  echo "$(c2f $(cpuTemperatureC))"
}

cpuPrint() {
  echo -n "CPU Temperature: $(cpuTemperatureF)$(degree)F"
}


# GPU
# ------------------------------------------------------------------------------
gpuTemperatureC() {
  if [ -f /opt/vc/bin/vcgencmd ]; then
    tempRaw="$(/opt/vc/bin/vcgencmd measure_temp)"
    tempC=$(echo "${tempRaw#*=}" | sed 's/'\''.*//g')
    echo $tempC
  fi
}

gpuTemperatureF() {
  echo "$(c2f $(gpuTemperatureC))" 
}

gpuPrint() {
  echo -n "GPU Temperature: $(gpuTemperatureF)$(degree)F"
}


# Helper Functions
# ------------------------------------------------------------------------------
c2f(){
  echo "scale=2;((9/5) * $1) + 32" |bc
}

degree() {
  printf '\xC2\xB0'
}

echo $(piPrint)
echo $(cpuPrint)
echo $(gpuPrint)
